name: 'versioning-toolkit'
description: 'Set of helpers for versioning'
author: 'Shoreline.io'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  actionName:
    description: 'action name'
    required: true
  prefix:
    description: 'prefix to filter tags'
    required: false
  push:
    description: 'push changes to git or not'
    required: false
    default: 'false'
  releasePrefix:
    description: 'release branch name and tag name prefix'
    required: false
  tag:
    description: 'the tag'
    required: false
  jiraTagFieldName:
    description: 'Jira tag field name'
    required: false
  jiraUserEmail:
    description: 'Jira user email'
    required: false
  jiraApiToken:
    description: 'Jira API token'
    required: false
  jiraOrgOrigin:
    description: 'Jira org origin. Example https://foo.atlassian.net'
    required: false
  jiraAdditionalTag:
    description: 'Additional tag that will be added to each Jira issue in changelog'
    required: false
  majorSegment:
    description: 'major segment of the release tag version. If not specified previous release tag value is used'
    required: false
  minorSegment:
    description: 'minor segment of the release tag version. If not specified previous release tag value is used'
    required: false



