name: 'on-master'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - 'master'
jobs:
  test-lint-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 16.x

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-node_modules-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-node_modules-v1-

      - name: Install dependencies
        run: yarn

      - name: Test and Lint
        run: yarn test && yarn lint

      - name: Auto increment version
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prefix: ${{ github.ref }}
          actionName: 'autoIncrementPatch'
          pushTag: 'true'

